language: go

go:
  - "1.14.x"

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

install:
  - make tools

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
